### ISSUE TITLE
Use Case Checklist

### ISSUE THREAD

**Issue by dzwillia** [flexiodata/flexio-web-app#279]
Here's the list of use cases from issue #252 in checklist form so we can check 'em off as we make them. Also, feel free to edit this comment and add more if you've made them and they're not on the list.

CHARTS AND GRAPHS

- [X] Create a chart with Chart.js from a CSV file
- [ ] Prototype charts and graphs on a web page within minutes
- [ ] Set up Highcharts with interactive controls
- [ ] Use Google Sheets as a data source for Highcharts
- [ ] Create charts and graphs from CSV files in Dropbox
- [ ] Add interactive charts and graphs to a Wix website
- [ ] Add refreshable charts and graphs to a SquareSpace website
- [ ] Create charts and graphs directly from an API

DATA VISUALIZATION

- [x] Display interactive D3.js visualizations on GitHub pages
- [ ] Add dynamic data visualizations to static web pages on Amazon S3
- [ ] Add interactive D3.js data visualizations to a Wix website 
- [ ] Create D3.js data visualizations from Google Sheets
- [ ] Create D3.js data visualizations from CSV files in Dropbox
- [ ] Visualize data from APIs

SAAS UTILITIES

- [ ] Identify duplicate contact records in Salesforce.com
- [ ] Clean and standardize contact addresses in Pipedrive
- [ ] Generate custom financial reports from Xero
- [ ] Automatically email reports from Xero to your team
- [ ] Extract data from Mixpanel into CSV files in Dropbox

SAAS CONNECTORS

- [ ] Connect Mixpanel with Google Sheets
- [ ] Connect HubSpot with Google Sheets
- [ ] Connect Intercom with HubSpot
- [ ] Connect Xero with other applications
- [ ] Connect QuickBooks Online with other applications

DATA-DRIVEN COMPONENTS

- [ ] Add a contact form to a website and receive responses by email
- [ ] Add a file upload form to a website without setting up a server
- [ ] Add a file download button to a web page
- [ ] Create an interactive dashboard using D3.js components
- [ ] Add interactive controls to an embedded Google Map

DATA FEEDS

- [ ] Set up an automated SFTP data feed from a MySQL database
- [ ] Copy files automatically from an SFTP folder into Dropbox
- [ ] Send data from a MySQL database as an email attachment
- [ ] Backup files from Dropbox to Amazon S3
- [ ] Load a CSV file from an email attachment into a database

DATA CLEANING

- [ ] Clean invalid characters from text values in a CSV file
- [ ] Format values in a CSV file to match a standard data type
- [ ] Standardize column names in a set of CSV files
- [ ] Identify JSON objects with invalid data values
- [ ] Identify duplicate values in a set of JSON objects

DATA VALIDATION

- [ ] Validate the format of files submitted in an upload form
- [ ] Validate that a CSV file contains expected columns
- [ ] Validate values in a JSON object match an expected data type
- [ ] Validate values in a JSON object are within an expected range
- [ ] Validate there are no date range gaps in a set of CSV files
- [ ] Validate the contents of a CSV file
- [ ] Create automated tests for a set of API requests

IMAGE PROCESSING

- [ ] Automatically process images sent as an email attachment
- [x] Generate thumbnails for a large set of images
- [ ] Catalog the meta data for a large set of images in Dropbox
- [ ] Standardize the image format for hundreds of images in Dropbox
- [ ] Add a date/time stamp to the file name for a large set of photos

WEB SCRAPING

- [ ] Extract and catalog meta data for a set of web pages
- [ ] Extract and catalog image links for a set web pages 
- [ ] Extract and catalog embedded Twitter data for a set of web pages
- [ ] Generate an RSS feed for all links in a set of web pages
- [ ] Monitor a set of web pages for changes and new content

API INTEGRATION

- [ ] Create a custom set of API mappings
- [ ] Combine and reformat JSON objects from different APIs
- [ ] Standardize the JSON format from different versions of an API
- [ ] Create a CSV file from a set of API requests
- [ ] Add records to a Google Sheet from a set of API requests
