### ISSUE TITLE
Pipe List TODO

### ISSUE THREAD

**Issue by wanderslth** [flexiodata/flexio-web-app#422]
Per discussion:

Step 1:
- [x] Get tooltip in truncated descriptions/truncated pipe names
- [x] Get sort in header
- [ ] Make 'execution' sum query only for last 30 days
- [ ] May want to clarify this 'last 30 days' somehow (at worst, blue 'i' tooltip would work, but not sure if that's ugly. dunno)

Step 2:
- [ ] Add mult-select (checkboxes) for Delete

Step 3:
- [ ] Add multi-select for Statistics (filtered by pipe name selected + date range)
