### ISSUE TITLE
Activity List TODO

### ISSUE THREAD

**Issue by wanderslth** [flexiodata/flexio-web-app#423]
Step 1:
- [x] Add in Date Range filter control
- [x] Add in Status filter control
- [x] UI- based pagination, 20 records per page
- [x] Add in a dropdown menu with 'details'; pop-open a modal that includes:
    * process header json
    * pipe json -- call is:  GET /:userid/processes/:eid
    * For this, I'm imagining some super simple text with headers (maybe a 'copy' button?) like:

Process
-------------
 api call foo json detail

Pipe
-------------
api json pipe detail

---

Step 2:
- [x] Pipe name stamped in process API (aaron)
- [x] Trigger name stamped in process API (aaron)

Step 3: 
- [ ] Add in pipe name filter control (any way to offer multi-select?)
- [ ] Add in trigger type filter control (any way to offer multi-select?)

Step 4:
- [ ] Add pagination in the API (aaron)
