### ISSUE TITLE
Meta information in <head> for in-app pages

### ISSUE THREAD

**Issue by dzwillia** [flexiodata/flexio-web-app#433]
This is along the same lines as issue #425.

I've got some of this covered, but just for the sake of being thorough, here's the list of pages I'd like to make sure we have titles and possibly descriptions (if desired):

**NOTE** If you don't see a field below, it means I haven't specified it on that page and it we fall back to App-wide field if it is specified

- [x] App-wide (these are default titles and descriptions on all pages unless specified below):
    - [X] **Title**: Flex.io
    - [X] **Description**: Flex.io enables you to stitch together serverless functions with out-of-the-box helper tasks that take the pain out of OAuth, notifications, scheduling, local storage, library dependencies and other "glue" code.
- [x] Sign In Page
    - [X] **Title**: Sign In | Flex.io
    - [X] **Description**: Sign in to Flex.io and stitch together serverless functions with out-of-the-box helper tasks that take the pain out of OAuth, notifications, scheduling, local storage, library dependencies and other "glue" code.
- [ ] Sign Up Page
    - [X] **Title**: Sign Up | Flex.io
- [ ] Forgot Password Page
    - [X] **Title**: Forgot Password | Flex.io
- [ ] Reset Password Page
    - [X] **Title**: Reset Password | Flex.io
- [ ] Account
    - [X] **Title**: My Account | Flex.io
- [ ] Pipes
    - [X] **Title**: Pipes | Flex.io
- [ ] Connections
    - [X] **Title**: Connections | Flex.io
- [ ] Storage
    - [X] **Title**: Storage | Flex.io
- [ ] Activity
    - [X] **Title**: Activity| Flex.io
- [ ] Pipe Document
    - [X] **Title**: *\<name of pipe\>* | Flex.io
- [ ] Builder Document (used for templates)
    - [X] **Title**: *\<name of template\>* | Flex.io

Again, this is what is currently in the app as of the production update earlier today. Sign off on items by checking the checkbox. If you have edits, just uncheck the existing item or add an unchecked item as part of the sub-list.

This is just to get started... we can add any other meta tags as well if we want (e.g. og:title, etc.)
